---

- name: bandit challenges
  hosts: all
  gather_facts: false
  tasks:

- name: "bandit0"
  ansible.builtin.import_playbook: playbooks/bandit0.yml

- name: "bandit1"
  ansible.builtin.import_playbook: playbooks/bandit1.yml

- name: "bandit2"
  ansible.builtin.import_playbook: playbooks/bandit2.yml


