- name: "check banditX_pw entry is in file"
  ansible.builtin.lineinfile:
    path: "{{ bandit_vault }}"
    regexp: '{{ bandit_dst_name }}_pw: .*'
    state: absent
  check_mode: true
  register: banditX_entry_state
  delegate_to: localhost

- name: "set banditX_entry in passwords.yml if not set"
  ansible.builtin.lineinfile:
    path: "{{ bandit_vault }}"
    line: '{{ bandit_dst_name }}_pw: '
    state: present
  when: not banditX_entry_state.changed
  delegate_to: localhost

- name: "replace banditX_pw"
  ansible.builtin.replace:
    path: "{{ bandit_vault }}"
    regexp: '{{ bandit_dst_name }}_pw: .*'
    replace: '{{ bandit_dst_name }}_pw: {{ password_bandit[0] }}'
  delegate_to: localhost

- name: "Entferne leere Zeilen aus Vault-Datei"
  ansible.builtin.replace:
    path: "{{ bandit_vault }}"
    regexp: '^\s*\n'
    replace: ''
  delegate_to: localhost


- name: "show password"
  ansible.builtin.debug:
    msg: "{{ password_bandit[0] }}"
