---

- name: bandit_1 challenges
  hosts: bandit1
  gather_facts: true
  vars_files:
    - "{{ bandit_vault }}"
  vars:
    ansible_ssh_pass: "{{ bandit1_pw }}"
    ansible_remote_tmp: "/tmp"
  tasks:
      
    - name: "show password from bandit1"
      ansible.builtin.debug:
        msg: "{{ ansible_ssh_pass }}"
    
    - name: "show name"
      ansible.builtin.debug:
        var: ansible_facts['user_id']

    - name: "get content of readme file:"
      ansible.builtin.slurp:
        src: ./-
      register: output

    - name: "store password in var"
      ansible.builtin.set_fact:
        password_bandit: ["{{ output['content'] | b64decode }}"]
 
    - name: "set Password in file"
      ansible.builtin.include_tasks:
        file: "../tasks/manage_passwords.yml"