
---

- name: bandit_1 challenges
  hosts: bandit1
  gather_facts: false
  vars:
    ansible_ssh_pass: "{{ password_bandit1 }}"
  tasks:
      
    - name: "show password from bandit1"
      ansible.builtin.debug:
        msg: "{{ ansible_ssh_pass }}"
    
    - name: "show name"
      ansible.builtin.debug:
        var: ansible_facts['user_id']


